"""Structured output from the literature analysis agent."""

from pydantic import BaseModel, Field

from indication_scout.models.model_evidence_summary import EvidenceSummary
from indication_scout.services.retrieval import AbstractResult


class LiteratureOutput(BaseModel):
    """Final assembled output from a single literature agent run."""

    search_results: list[str] = Field(
        default_factory=list,
        description="PubMed keyword queries generated by expand_search_terms.",
    )
    pmids: list[str] = Field(
        default_factory=list,
        description="Deduplicated PMIDs returned by fetch_and_cache.",
    )
    semantic_search_results: list[AbstractResult] = Field(
        default_factory=list,
        description="Top-k abstracts ranked by similarity from semantic_search.",
    )
    evidence_summary: EvidenceSummary | None = Field(
        default=None,
        description="Structured evidence summary from synthesize.",
    )
    summary: str = Field(
        default="",
        description="LLM narrative summary from the final agent message.",
    )
