"""create pubmed_abstracts table

Revision ID: f0ccb024a181
Revises: 74ac9560da3a
Create Date: 2026-02-23 21:39:51.231444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f0ccb024a181'
down_revision: Union[str, Sequence[str], None] = '74ac9560da3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('pubmed_abstracts',
    sa.Column('pmid', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Text(), nullable=True),
    sa.Column('mesh_terms', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pmid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubmed_abstracts')
    # ### end Alembic commands ###
